### ***Análise dos Dados***

In [12]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..', 'scripts')))

In [ ]:
import carregar_dados

In [ ]:
# Chama a função e armazena o resultado em uma única variável
dados_consolidados = carregar_dados.carregar_e_consolidar_dados()

In [11]:
# Verifica se os dados foram carregados corretamente
print("Amostra dos dados consolidados:")
dados_consolidados.head()

Amostra dos dados consolidados:

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon,Loja
0,Assistente virtual,eletronicos,219.08,9.249790,16/01/2021,Pedro Gomes,SP,4,cartao_credito,8,-22.19,-48.79,Loja 1
1,Mesa de jantar,moveis,256.35,11.234305,18/05/2022,Beatriz Moraes,RJ,1,cartao_credito,4,-22.25,-42.66,Loja 1
2,Jogo de tabuleiro,brinquedos,279.51,21.262681,15/03/2021,João Souza,DF,1,cartao_credito,1,-15.83,-47.86,Loja 1
3,Micro-ondas,eletrodomesticos,1009.99,54.667344,03/05/2022,João Souza,RS,4,boleto,1,-30.17,-53.50,Loja 1
4,Cadeira de escritório,moveis,446.99,26.964689,07/11/2020,Larissa Alves,MG,5,boleto,1,-18.10,-44.38,Loja 1

#### ***Loja 1***

In [32]:
print("\nAmostra dos dados da Loja 1:")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 1'].head()

Amostra dos dados da Loja 1:

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon,Loja
0,Assistente virtual,eletronicos,219.08,9.249790,16/01/2021,Pedro Gomes,SP,4,cartao_credito,8,-22.19,-48.79,Loja 1
1,Mesa de jantar,moveis,256.35,11.234305,18/05/2022,Beatriz Moraes,RJ,1,cartao_credito,4,-22.25,-42.66,Loja 1
2,Jogo de tabuleiro,brinquedos,279.51,21.262681,15/03/2021,João Souza,DF,1,cartao_credito,1,-15.83,-47.86,Loja 1
3,Micro-ondas,eletrodomesticos,1009.99,54.667344,03/05/2022,João Souza,RS,4,boleto,1,-30.17,-53.50,Loja 1
4,Cadeira de escritório,moveis,446.99,26.964689,07/11/2020,Larissa Alves,MG,5,boleto,1,-18.10,-44.38,Loja 1

In [45]:
print("\nInformações sobre a Loja 1:\n")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 1'].info()

Informações sobre a Loja 1:

<class 'pandas.core.frame.DataFrame'>
Index: 2359 entries, 0 to 2358
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
 12  Loja                    2359 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 258.0+ KB

In [38]:
print("\nValores nulos na Loja 1:")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 1'].isnull().sum()

Valores nulos na Loja 1:

Produto                   0
Categoria do Produto      0
Preço                     0
Frete                     0
Data da Compra            0
Vendedor                  0
Local da compra           0
Avaliação da compra       0
Tipo de pagamento         0
Quantidade de parcelas    0
lat                       0
lon                       0
Loja                      0
dtype: int64

#### ***Loja 2***

In [36]:
print("\nAmostra dos dados da Loja 2:")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 2'].head()

Amostra dos dados da Loja 2:

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon,Loja
2359,Cadeira de escritório,moveis,378.20,20.421138,04/08/2021,Thiago Silva,MG,1,boleto,1,-18.10,-44.38,Loja 2
2360,Pandeiro,instrumentos musicais,102.37,3.035334,26/11/2020,Bianca Santos,RJ,3,cartao_credito,4,-22.25,-42.66,Loja 2
2361,Cama king,moveis,591.13,31.759020,22/10/2021,Thiago Silva,SC,5,cartao_credito,10,-27.45,-50.95,Loja 2
2362,Cama king,moveis,1208.24,61.919584,04/05/2022,Larissa Alves,RS,5,cartao_credito,10,-30.17,-53.50,Loja 2
2363,Cadeira de escritório,moveis,530.41,25.827176,26/02/2022,Lucas Oliveira,SP,4,cartao_credito,3,-22.19,-48.79,Loja 2

In [44]:
print("\nInformações sobre a Loja 2:\n")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 2'].info()

Informações sobre a Loja 2:

<class 'pandas.core.frame.DataFrame'>
Index: 2359 entries, 2359 to 4717
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
 12  Loja                    2359 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 258.0+ KB

In [46]:
print("\nValores nulos na Loja 2:")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 2'].isnull().sum()

Valores nulos na Loja 2:

Produto                   0
Categoria do Produto      0
Preço                     0
Frete                     0
Data da Compra            0
Vendedor                  0
Local da compra           0
Avaliação da compra       0
Tipo de pagamento         0
Quantidade de parcelas    0
lat                       0
lon                       0
Loja                      0
dtype: int64

#### ***Loja 3***

In [50]:
print("\nAmostra dos dados da Loja 3:")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 3'].head()

Amostra dos dados da Loja 3:

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon,Loja
4718,Secadora de roupas,eletrodomesticos,1713.50,88.823159,17/12/2021,Camila Ribeiro,CE,4,cartao_credito,4,-5.20,-39.53,Loja 3
4719,Cômoda,moveis,386.81,18.180908,10/02/2021,Larissa Alves,RS,3,cartao_credito,1,-30.17,-53.50,Loja 3
4720,Violão,instrumentos musicais,404.62,23.197592,22/01/2023,Lucas Oliveira,SP,5,cartao_credito,3,-22.19,-48.79,Loja 3
4721,Bola de vôlei,esporte e lazer,78.40,4.463341,22/03/2022,Pedro Gomes,BA,4,cartao_credito,6,-13.29,-41.71,Loja 3
4722,Guarda roupas,moveis,694.76,34.578319,12/01/2022,Bianca Santos,SP,1,cartao_credito,1,-22.19,-48.79,Loja 3

In [49]:
print("\nInformações sobre a Loja 3:\n")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 3'].info()

Informações sobre a Loja 3:

<class 'pandas.core.frame.DataFrame'>
Index: 2359 entries, 4718 to 7076
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
 12  Loja                    2359 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 258.0+ KB

In [47]:
print("\nValores nulos na Loja 3:")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 3'].isnull().sum()

Valores nulos na Loja 3:

Produto                   0
Categoria do Produto      0
Preço                     0
Frete                     0
Data da Compra            0
Vendedor                  0
Local da compra           0
Avaliação da compra       0
Tipo de pagamento         0
Quantidade de parcelas    0
lat                       0
lon                       0
Loja                      0
dtype: int64

#### ***Loja 4***

In [51]:
print("\nAmostra dos dados da Loja 4:")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 4'].head()

Amostra dos dados da Loja 4:

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon,Loja
7077,Lava louças,eletrodomesticos,1446.46,74.604083,11/11/2022,Rafael Costa,SP,4,cartao_credito,3,-22.19,-48.79,Loja 4
7078,Cama box,moveis,631.70,33.919251,03/01/2020,Thiago Silva,GO,5,cartao_credito,2,-15.98,-49.86,Loja 4
7079,Bola de basquete,esporte e lazer,31.54,0.000000,25/12/2022,Larissa Alves,MG,5,boleto,1,-18.10,-44.38,Loja 4
7080,Modelagem preditiva,livros,76.93,1.680730,23/11/2021,Lucas Oliveira,MG,3,boleto,1,-18.10,-44.38,Loja 4
7081,Fone de ouvido,eletronicos,185.14,7.442587,25/04/2022,Bianca Santos,SP,4,cartao_credito,7,-22.19,-48.79,Loja 4

In [42]:
print("\nInformações sobre a Loja 4:\n")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 4'].info()

Informações sobre a Loja 4:

<class 'pandas.core.frame.DataFrame'>
Index: 2358 entries, 7077 to 9434
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2358 non-null   object
 1   Categoria do Produto    2358 non-null   object
 2   Preço                   2358 non-null   float64
 3   Frete                   2358 non-null   float64
 4   Data da Compra          2358 non-null   object
 5   Vendedor                2358 non-null   object
 6   Local da compra         2358 non-null   object
 7   Avaliação da compra     2358 non-null   int64
 8   Tipo de pagamento       2358 non-null   object
 9   Quantidade de parcelas  2358 non-null   int64
 10  lat                     2358 non-null   float64
 11  lon                     2358 non-null   float64
 12  Loja                    2358 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 257.9+ KB

In [48]:
print("\nValores nulos na Loja 4:")
dados_consolidados[dados_consolidados['Loja'] == 'Loja 4'].isnull().sum()

Valores nulos na Loja 4:

Produto                   0
Categoria do Produto      0
Preço                     0
Frete                     0
Data da Compra            0
Vendedor                  0
Local da compra           0
Avaliação da compra       0
Tipo de pagamento         0
Quantidade de parcelas    0
lat                       0
lon                       0
Loja                      0
dtype: int64